# theme: minima
theme: ./src

siteConfig:
  url: https://example.com
  author: Author of This Site
  email: author@your-domain.com
  description: Write an awesome description for your new site here. You can edit this line in saber-config.yml. It will appear in your document head meta (for Google search results) site description.

themeConfig:
  nav:
    - text: 简介
      link: /intro
    - text: 基础部分
      link: /basic
    - text: 搜索
      link: /search
    - text: 动态规划
      link: /dp
    - text: 字符串
      link: /string
    - text: 数学
      link: /math
    - text: 数据结构
      link: /ds

  sidebarMenu:
    [
      {
        title: "简介",
        children:
          [
            { title: "Getting Started", link: "/" },
            { title: "ICPC/CCPC 赛事与赛制", link: "/intro/icpc" },
            { title: "常见错误", link: "/intro/common-mistakes" },
          ],
      },
      {
        title: "搜索",
        children:
          [
            { title: "A*", link: "/search/astar" },
            { title: "BIT", link: "/search/bit" },
          ],
      },
    ]
  social:
    twitter: saber_land
    github: egoist
    rss: true
plugins:
  - resolve: saber-plugin-query-posts
  - resolve: saber-plugin-prismjs
    options:
      lineNumbers: true
  - resolve: saber-plugin-feed
    options:
      atomFeed: true
markdown:
  plugins:
    - resolve: markdown-it-math
